//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consume_Servicio_i2es.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_clientes.php")]
        public string Consume_Servicio_i2es_Clientes_ws_actualizacion_clientes {
            get {
                return ((string)(this["Consume_Servicio_i2es_Clientes_ws_actualizacion_clientes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_estados_pedidos.php")]
        public string Consume_Servicio_i2es_Pedidos_Estado_ws_estados_pedidos {
            get {
                return ((string)(this["Consume_Servicio_i2es_Pedidos_Estado_ws_estados_pedidos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_cuponessorteo.php")]
        public string Consume_Servicio_i2es_ws_envio_cupones_ws_actualizacion_cuponessorteo {
            get {
                return ((string)(this["Consume_Servicio_i2es_ws_envio_cupones_ws_actualizacion_cuponessorteo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_cotizacion.php")]
        public string Consume_Servicio_i2es_Cotizacion_ws_actualizar_cotizacion {
            get {
                return ((string)(this["Consume_Servicio_i2es_Cotizacion_ws_actualizar_cotizacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_articulos.php")]
        public string Consume_Servicio_i2es_Actualizacion_Articulos_ws_actualizacion_articulos {
            get {
                return ((string)(this["Consume_Servicio_i2es_Actualizacion_Articulos_ws_actualizacion_articulos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_articulosbaja.php")]
        public string Consume_Servicio_i2es_Baja_Articulos_ws_actualizacion_articulosbaja {
            get {
                return ((string)(this["Consume_Servicio_i2es_Baja_Articulos_ws_actualizacion_articulosbaja"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_stockprecio.php")]
        public string Consume_Servicio_i2es_Actualizacion_Stock_Precio_ws_actualizacion_stockprecio {
            get {
                return ((string)(this["Consume_Servicio_i2es_Actualizacion_Stock_Precio_ws_actualizacion_stockprecio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://shop.aluminios.com:443/ws/ws_actualizacion_stockunidad.php")]
        public string Consume_Servicio_i2es_Actualizacion_stock_unidad_ws_actualizacion_stockunidad {
            get {
                return ((string)(this["Consume_Servicio_i2es_Actualizacion_stock_unidad_ws_actualizacion_stockunidad"]));
            }
        }
    }
}
