//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Consume_Servicio_i2es.Actualizacion_stock_unidad {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ws_actualizacion_stockunidadBinding", Namespace="urn:ws_actualizacion_stockunidad")]
    public partial class ws_actualizacion_stockunidad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Callws_actualizacion_stockunidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ws_actualizacion_stockunidad() {
            this.Url = global::Consume_Servicio_i2es.Properties.Settings.Default.Consume_Servicio_i2es_Actualizacion_stock_unidad_ws_actualizacion_stockunidad;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Callws_actualizacion_stockunidadCompletedEventHandler Callws_actualizacion_stockunidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:ws_actualizacion_stockunidad#ws_actualizacion_stockunidad", RequestNamespace="urn:ws_actualizacion_stockunidad", ResponseNamespace="urn:ws_actualizacion_stockunidad")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Salida Callws_actualizacion_stockunidad(string Usuariows, string Passws, string Xml) {
            object[] results = this.Invoke("Callws_actualizacion_stockunidad", new object[] {
                        Usuariows,
                        Passws,
                        Xml});
            return ((Salida)(results[0]));
        }
        
        /// <remarks/>
        public void Callws_actualizacion_stockunidadAsync(string Usuariows, string Passws, string Xml) {
            this.Callws_actualizacion_stockunidadAsync(Usuariows, Passws, Xml, null);
        }
        
        /// <remarks/>
        public void Callws_actualizacion_stockunidadAsync(string Usuariows, string Passws, string Xml, object userState) {
            if ((this.Callws_actualizacion_stockunidadOperationCompleted == null)) {
                this.Callws_actualizacion_stockunidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallws_actualizacion_stockunidadOperationCompleted);
            }
            this.InvokeAsync("Callws_actualizacion_stockunidad", new object[] {
                        Usuariows,
                        Passws,
                        Xml}, this.Callws_actualizacion_stockunidadOperationCompleted, userState);
        }
        
        private void OnCallws_actualizacion_stockunidadOperationCompleted(object arg) {
            if ((this.Callws_actualizacion_stockunidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Callws_actualizacion_stockunidadCompleted(this, new Callws_actualizacion_stockunidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ws_actualizacion_stockunidad")]
    public partial class Salida {
        
        private string errorField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Callws_actualizacion_stockunidadCompletedEventHandler(object sender, Callws_actualizacion_stockunidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Callws_actualizacion_stockunidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Callws_actualizacion_stockunidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Salida Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Salida)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591